/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MarketingSetRouteImport } from './routes/marketing-set'
import { Route as StrategicPartnershipRouteImport } from './routes/strategic-partnership'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSetRoute = MarketingSetRouteImport.update({
  id: '/marketing-set',
  path: '/marketing-set',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategicPartnershipRoute = StrategicPartnershipRouteImport.update({
  id: '/strategic-partnership',
  path: '/strategic-partnership',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/marketing-set': typeof MarketingSetRoute
  '/strategic-partnership': typeof StrategicPartnershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/marketing-set': typeof MarketingSetRoute
  '/strategic-partnership': typeof StrategicPartnershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/marketing-set': typeof MarketingSetRoute
  '/strategic-partnership': typeof StrategicPartnershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/marketing-set' | '/strategic-partnership'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/marketing-set' | '/strategic-partnership'
  id: '__root__' | '/' | '/about' | '/marketing-set' | '/strategic-partnership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MarketingSetRoute: typeof MarketingSetRoute
  StrategicPartnershipRoute: typeof StrategicPartnershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-set': {
      id: '/marketing-set'
      path: '/marketing-set'
      fullPath: '/marketing-set'
      preLoaderRoute: typeof MarketingSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategic-partnership': {
      id: '/strategic-partnership'
      path: '/strategic-partnership'
      fullPath: '/strategic-partnership'
      preLoaderRoute: typeof StrategicPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MarketingSetRoute: MarketingSetRoute,
  StrategicPartnershipRoute: StrategicPartnershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
